server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  application:
    name: image-processor
  data:
    mongodb:
      uri: mongodb://root:root@localhost
      database: image-processor
aws:
  bucket:
    name: furqas-image-processor-bucket
